- name: Copy network interfaces file
  template:
    src: "etc/network/interfaces.j2"
    dest: "/etc/network/interfaces"
    mode: 0644

- name: Copy network alias-0 file
  template:
    src: "etc/network/interfaces.d/eno1_alias_0"
    dest: "/etc/network/interfaces.d/eno1_alias_0"
    mode: 0644

- name: Copy network alias-1 file
  template:
    src: "etc/network/interfaces.d/eno1_alias_1"
    dest: "/etc/network/interfaces.d/eno1_alias_1"
    mode: 0644

- name: Ensure hosts file entries
  blockinfile:
    path: /etc/hosts
    block: |
      # HAProxy
      10.10.10.72     knahrvorn-eno1-0 nextcloud.pbnet.dk knahrvorn.pbnet.dk
      # Apache
      10.10.10.73     knahrvorn-eno1-1 nextcloud.c4a.local
      # Knahrvorn
      10.10.10.80     knahrvorn-eno1 knahrvorn knahrvorn.c4a.local nomad.pbnet.dk hub.flexdevel.com birth.flexdevel.com api.pbnet.dk
