- name: Download Nextcloud archive
  get_url:
    url: https://github.com/nextcloud/server/archive/refs/tags/v29.0.3.tar.gz
    dest: /tmp/nextcloud-v29.0.3.tar.gz

- name: Create target directory for Nextcloud
  file:
    path: /var/www/nextcloud
    state: directory
    owner: www-data
    group: www-data
    mode: '0750'

- name: Extract Nextcloud archive
  ansible.builtin.unarchive:
    src: /tmp/nextcloud-v29.0.3.tar.gz
    dest: /var/www/nextcloud
    remote_src: yes
    extra_opts: ['--strip-components=1']

- name: Set ownership for all files and directories in Nextcloud
  command: chown -R www-data:www-data /var/www/nextcloud

- name: Set directory permissions to 750
  command: find /var/www/nextcloud -type d -exec chmod 750 {} +

- name: Set file permissions to 644
  command: find /var/www/nextcloud -type f -exec chmod 644 {} +