- name: Create target directory for Nextcloud
  file:
    path: /var/www/nextcloud
    state: directory
    owner: www-data
    group: www-data
    mode: '0750'

- name: Check for files in nextcloud folder
  command: "sh -c 'ls -A /var/www/nextcloud | head -n 1'"
  register: nextcloud_found_files
  ignore_errors: true
  changed_when: false

- name: Download Nextcloud archive
  get_url:
    url: https://github.com/nextcloud/server/archive/refs/tags/v29.0.3.tar.gz
    dest: /tmp/nextcloud-v29.0.3.tar.gz
  when: nextcloud_found_files.stdout == ""

- name: Extract Nextcloud archive
  unarchive:
    src: /tmp/nextcloud-v29.0.3.tar.gz
    dest: /var/www/nextcloud
    remote_src: yes
    extra_opts: ['--strip-components=1']
  when: nextcloud_found_files.stdout == ""

- name: Set ownership for all files and directories in Nextcloud
  command: chown -R www-data:www-data /var/www/nextcloud

- name: Set directory permissions to 750
  command: find /var/www/nextcloud -type d -exec chmod 750 {} +

- name: Set file permissions to 644
  command: find /var/www/nextcloud -type f -exec chmod 644 {} +

- name: Adding PHP configuration parameters
  copy:
    src: "etc/php/8.2/fpm/conf.d/90-nextcloud.ini"
    dest: "/etc/php/8.2/fpm/conf.d/90-nextcloud.ini"
    mode: 0644

- name: Restart php-fpm service
  systemd_service:
    name: php8.2-fpm
    state: restarted

- name: Making Nextcloud Apache configuration
  template:
    src: "etc/apache2/sites-available/001-nextcloud.conf.j2"
    dest: "/etc/apache2/sites-available/001-nextcloud.conf"
    mode: 0644

- name: Enable Nextcloud Apache site
  command:
    cmd: a2ensite 001-nextcloud

- name: Restart Apache service
  systemd_service:
    name: apache2
    state: restarted

- name: Making MariaDB configuration template
  template:
    src: "tmp/mysql.sql.j2"
    dest: "/tmp/mysql.sql"

- name: Check if MariaDB root password is already set
  mysql_user:
    name: root
    check_implicit_admin: yes
    login_unix_socket: /var/run/mysqld/mysqld.sock
  register: mysql_root_check
  ignore_errors: true
  changed_when: false

- name: Execute MariaDB configuration template
  shell: mysql --socket=/var/run/mysqld/mysqld.sock mysql < /tmp/mysql.sql
  when: not mysql_root_check.failed
  become: true

- name: Copy my.cnf file
  template:
    src: root/.my.cnf
    dest: /root/.my.cnf
    mode: 0600

- name: Making cuTURN configuration
  template:
    src: "etc/turnserver.conf.j2"
    dest: "/etc/turnserver.conf"
    mode: 0644

- name: Setting up Nextcloud background job
  cron:
    name: Nextcloud background job
    user: www-data
    minute: "*/5"
    job: "php -f /var/www/nextcloud/cron.php --define apc.enable_cli=1"
