- name: Install k0s binary
  hosts: k0s-cluster
  become: yes
  tasks:
    - name: Download and install k0s
      shell: curl -sSLf https://get.k0s.sh | sh
      args:
        executable: /bin/bash

- name: Set up controller
  hosts: k0s-controller
  become: yes
  tasks:
    - name: Install k0s controller with worker role
      shell: k0s install controller --enable-worker

    - name: Start k0s controller
      shell: k0s start

    - name: Wait for k0s to start
      wait_for:
        port: 9443
        delay: 5
        timeout: 60

    - name: Generate worker join token
      command: k0s token create --role=worker
      register: worker_token

    - name: Save token to a file
      copy:
        dest: /tmp/token.txt
        content: "{{ worker_token.stdout }}"

    - name: Fetch token.txt
      fetch:
        src: /tmp/token.txt
        dest: ./token.txt
        flat: yes

- name: Distribute token and install workers
  hosts: k0s-worker
  become: yes
  tasks:
    - name: Copy token to worker
      copy:
        src: ./token.txt
        dest: /tmp/token.txt
        mode: '0600'

    - name: Install k0s worker using token
      shell: k0s install worker --token-file /tmp/token.txt

    - name: Start k0s worker
      shell: k0s start