- hosts: k0s-cluster
  name: Run common tasks
  become: true
  tags:
    common
  tasks:
    - import_role:
        name: common

- hosts: k0s-cluster
  gather_facts: false
  name: Setup k0s cluster
  become: true
  tags:
    k0s
  tasks:
    - name: Check if k0s is already installed
      stat:
        path: /usr/local/bin/k0s
      register: k0s
    - import_role:
        name: k0s
      when: not k0s.stat.exists

- hosts: k0s-controller
  gather_facts: false
  name: Setup k0s controller
  become: true
  tags:
    k0s-controller
  tasks:
    - import_role:
        name: k0s-controller
      when: not k0s.stat.exists
  
- hosts: k0s-worker
  gather_facts: false
  name: Setup k0s worker
  become: true
  tags:
    k0s-worker
  tasks:
    - import_role:
        name: k0s-worker
      when: not k0s.stat.exists