services:
  ntfy:
    image: binwiederhier/ntfy:latest
    restart: unless-stopped
    environment:
      NTFY_BASE_URL: https://ntfy.pbnet.dk
      NTFY_CACHE_FILE: /var/lib/ntfy/cache.db
      NTFY_AUTH_FILE: /var/lib/ntfy/auth.db
      NTFY_AUTH_DEFAULT_ACCESS: deny-all
      NTFY_BEHIND_PROXY: true
      NTFY_ATTACHMENT_CACHE_DIR: /var/lib/ntfy/attachments
      NTFY_ENABLE_LOGIN: true      
    container_name: ntfy
    volumes:
      - /export/volumes/docker/ntfy:/var/lib/ntfy
    ports:
      - 8080:80
    command: serve