- hosts: all
  name: Run common tasks
  become: true
  tags:
    - "common"
  tasks:
    - import_role:
        name: common

- hosts: all
  gather_facts: false
  name: Do ssh setup
  become: true
  tags:
    - "ssh"
  tasks:
    - import_role:
        name: ssh

- hosts: all
  gather_facts: false
  name: Do network setup
  become: true
  tags:
    - "network"
  tasks:
    - import_role:
        name: network

- hosts: all
  gather_facts: false
  name: Do Apache & PHP setup
  become: true
  tags:
    - "apache"
  tasks:
    - import_role:
        name: apache

- hosts: all
  name: Do Docker setup
  become: true
  tags:
    - "docker"
  tasks:
    - import_role:
        name: docker

- hosts: all
  name: Do Consul & Nomad setup
  become: true
  tags:
    - "nomad"
  tasks:
    - import_role:
        name: nomad

- hosts: all
  gather_facts: false
  name: Do Nextcloud setup
  become: true
  tags:
    - "nextcloud"
  tasks:
    - import_role:
        name: nextcloud

- hosts: all
  gather_facts: false
  name: Do TiddlyWiki setup
  become: true
  tags:
    - "tiddlywiki"
  tasks:
    - import_role:
        name: tiddlywiki
