- name: Install k0s controller with worker role
  shell: k0s install controller --enable-worker

- name: Start k0s controller
  shell: k0s start

- name: Wait for k0s to start
  wait_for:
    port: 9443
    delay: 5
    timeout: 60

- name: Generate worker join token
  command: k0s token create --role=worker
  register: worker_token

- name: Save token to a file
  copy:
    dest: /tmp/token.txt
    content: "{{ worker_token.stdout }}"

- name: Fetch token.txt
  fetch:
    src: /tmp/token.txt
    dest: ./token.txt
    flat: yes