- name: Add user to www-data group
  user:
    name: pmh
    groups: www-data
    append: yes

- name: Enable Apache proxy modules
  command:
    cmd: a2enmod proxy_fcgi setenvif

- name: Enable PHP
  command:
    cmd: a2enconf php8.2-fpm

- name: Remove "Listen 80" from ports.conf
  lineinfile:
    path: /etc/apache2/ports.conf
    regexp: "^Listen 80"
    state: absent

- name: Ensure Listen localhost is present
  lineinfile:
    path: /etc/apache2/ports.conf
    regexp: "^Listen 127.0.0.1:80"
    line: "Listen 127.0.0.1:80"
    state: present

- name: Ensure Listen alias:0 is present
  lineinfile:
    path: /etc/apache2/ports.conf
    regexp: "^Listen {{ network.ip_alias_1 }}:80"
    line: "Listen {{ network.ip_alias_1 }}:80"
    state: present

- name: Making Knahrvorn Apache configuration
  template:
    src: "etc/apache2/sites-available/000-knahrvorn.conf.j2"
    dest: "/etc/apache2/sites-available/000-knahrvorn.conf"
    mode: 0644

- name: Disable default site
  command:
    cmd: a2dissite 000-default

- name: Enable Knahrvorn Apache site
  command:
    cmd: a2ensite 000-knahrvorn

- name: Reload Apache to apply changes
  ansible.builtin.service:
    name: apache2
    state: reloaded
