- name: Add user to www-data group
  user:
    name: pmh
    groups: www-data
    append: yes

- name: Enable Apache proxy modules
  command:
    cmd: a2enmod proxy proxy_http proxy_wstunnel proxy_fcgi setenvif rewrite

- name: Enable PHP
  command:
    cmd: a2enconf php8.2-fpm

- name: Configure php-fpm pm settings
  ansible.builtin.blockinfile:
    path: /etc/php/8.2/fpm/pool.d/www.conf
    marker: "; {mark} ANSIBLE MANAGED PM SETTINGS"
    block: |
      pm = dynamic
      pm.max_children = 120
      pm.start_servers = 12
      pm.min_spare_servers = 6
      pm.max_spare_servers = 18
  notify: Restart php-fpm

- name: Remove "Listen 80" from ports.conf
  lineinfile:
    path: /etc/apache2/ports.conf
    regexp: "^Listen 80"
    state: absent

- name: Ensure Listen localhost is present
  lineinfile:
    path: /etc/apache2/ports.conf
    regexp: "^Listen 127.0.0.1:80"
    line: "Listen 127.0.0.1:80"
    state: present

- name: Ensure Listen alias:0 is present
  lineinfile:
    path: /etc/apache2/ports.conf
    regexp: "^Listen {{ network.ip_alias_1 }}:80"
    line: "Listen {{ network.ip_alias_1 }}:80"
    state: present

- name: Copy custom configuration
  copy:
    src: etc/apache2/conf-available/knahrvorn.conf
    dest: /etc/apache2/conf-available/knahrvorn.conf

- name: Enable custom configuration
  file:
    src: /etc/apache2/conf-available/knahrvorn.conf
    dest: /etc/apache2/conf-enabled/knahrvorn.conf
    state: link

- name: Making Knahrvorn Apache configuration
  template:
    src: etc/apache2/sites-available/000-knahrvorn.conf.j2
    dest: /etc/apache2/sites-available/000-knahrvorn.conf
    mode: 0644

- name: Disable default site
  command:
    cmd: a2dissite 000-default

- name: Enable Knahrvorn Apache site
  command:
    cmd: a2ensite 000-knahrvorn

- name: Give Apache write access to folder
  file:
    path: /var/www/html
    owner: www-data
    group: www-data
    mode: 0775

- name: Copy php scripts
  copy:
    src: "var/www/html/{{ item }}"
    dest: "/var/www/html/{{ item }}"
    owner: www-data
    group: www-data
  loop:
    - phpconf.php
    - request.php

- name: Reload Apache to apply changes
  ansible.builtin.service:
    name: apache2
    state: reloaded
