- name: Install prerequisites for Docker repository
  apt:
    update_cache: yes
    state: latest
    pkg: 
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg2
    - software-properties-common

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
    filename: docker

- name: Install Docker CE
  apt:
    state: latest
    pkg: 
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose-plugin

- name: Add user to docker group
  user:
    name: pmh
    groups: docker
    append: yes