- name: Install prerequisites for Docker repository
  apt:
    update_cache: yes
    state: latest
    pkg: 
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg2
    - software-properties-common

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
    filename: docker

- name: Install Docker CE
  apt:
    state: latest
    pkg: 
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose-plugin
  register: docker_result

- name: Add user to docker group
  user:
    name: pmh
    groups: docker
    append: yes

- name: Docker dns configuration
  copy:
    src: "etc/docker/daemon.json"
    dest: "/etc/docker/daemon.json"
    mode: 0644
  register: docker_result

- name: Restart Docker to apply changes
  service:
    name: docker
    state: restarted
  when: docker_result.changed

- name: Create directories for docker volumes
  file:
    path: "/export/volumes/docker/{{ item.path }}"
    state: directory
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('docker') }}"
    mode: "{{ item.mode | default('42775') }}"
  loop:
    - path: redeem/pgdata
    - path: redeem/redis/conf
    - path: redeem/session
      owner: www-data
      group: www-data
      mode: '0700'
    - path: dstar4all/html
    - path: registry/auth
    - path: registry/certs
    - path: registry/data
    - path: vaultwarden
    - path: ntfy

- name: Ensure folders for docker compose scripts
  file:
    path: /home/pmh/docker/{{ item }}
    state: directory
    owner: pmh
    group: pmh
  loop:
    - redeem
    - redeem/database
    - dstar4all
    - registry
    - vaultwarden
    - collabora
    - ntfy

- name: YAML files
  template:
    src: home/pmh/docker/{{ item }}/docker-compose.yaml
    dest: /home/pmh/docker/{{ item }}/docker-compose.yaml
    owner: pmh
    group: pmh
    mode: 0644
  loop:
    - redeem
    - dstar4all
    - registry
    - vaultwarden
    - collabora
    - ntfy

- name: Docker compose scripts
  copy: 
    src: home/pmh/docker/{{ item }}/update-deployment.sh
    dest: /home/pmh/docker/{{ item }}/update-deployment.sh
    owner: pmh
    group: pmh
    mode: 0750
  loop:
    - redeem
    - dstar4all
    - registry
    - vaultwarden
    - collabora
    - ntfy

- name: Set sysctl kernel parameter
  sysctl:
    name: vm.overcommit_memory
    value: '1'
    sysctl_set: yes