services:
  registry:
    restart: always
    image: registry:2
    container_name: registry
    ports:
      - 5000:5000
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/flexdevel.crt.pem
      REGISTRY_HTTP_TLS_KEY: /certs/flexdevel.key.pem
        #REGISTRY_AUTH: htpasswd
        #REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
        #REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
    volumes:
      - /mnt/nas1/volumes/docker/registry/data:/var/lib/registry
      - /mnt/nas1/volumes/docker/registry/certs:/certs
      - /mnt/nas1/volumes/docker/registry/auth:/auth
