- name: Install packages
  apt:
    update_cache: yes
    state: latest
    pkg:
    - net-tools
    - bind9-dnsutils
    - bsd-mailx
    - build-essential
    - pkg-config
    - libicu-dev
    - bison
    - flex
    - libreadline-dev
    - libz-dev
    - chrony
    - mc
    - nagios-nrpe-server
    - ntpdate
    - postfix
    - rdiff-backup
    - wget
    - whois
    - apt-show-versions
    - apache2
    - mariadb-server
    - python3-pymysql
    - memcached
    - nodejs
    - npm
    - php-apcu
    - php-bcmath
    - php-bz2
    - php-cli
    - php-curl
    - php-fpm
    - php-gd
    - php-gmp
    - php-imagick
    - php-imap
    - php-intl
    - php-ldap
    - php-mbstring
    - php-redis
    - php-memcached
    - php-mysql
    - php-opcache
    - php-readline
    - php-xml
    - php-json
    - php-zip
    - php-pear
    - redis-tools
    - certbot
    - coturn
    - nfs-common


- name: Copy sudo setup
  copy:
    src: 'etc/sudoers.d/nopasswd'
    dest: '/etc/sudoers.d/nopasswd'
    mode: 0440

- name: Copy renew cert script
  copy:
    src: 'root/renew_cert.sh'
    dest: '/root/renew_cert.sh'
    mode: 0755

- name: Ensure NAS mountpoint
  file:
    path: "/mnt/nas1"
    state: directory
    owner: root
    group: root
  
- name: Add NAS fstab entry
  blockinfile:
    path: /etc/fstab
    block: |
      #10.100.1.1:/mnt/tank/balder /mnt/nas1 nfs defaults 0 0
