- name: Install packages
  apt:
    update_cache: yes
    state: latest
    pkg:
    - net-tools
    - bind9-dnsutils
    - bsd-mailx
    - build-essential
    - chrony
    - mc
    - nagios-nrpe-server
    - ntpdate
    - postfix
    - rdiff-backup
    - wget
    - whois
    - apt-show-versions
    - apache2
    - mariadb-server
    - python3-pymysql
    - memcached
    - nodejs
    - php-apcu
    - php-bcmath
    - php-bz2
    - php-cli
    - php-curl
    - php-fpm
    - php-gd
    - php-gmp
    - php-imagick
    - php-imap
    - php-intl
    - php-ldap
    - php-mbstring
    - php-redis
    - php-memcached
    - php-mysql
    - php-opcache
    - php-readline
    - php-xml
    - php-json
    - php-zip
    - php-pear
    - redis-tools
    - certbot
    - coturn

- name: Copy sudo setup
  copy:
    src: 'etc/sudoers.d/nopasswd'
    dest: '/etc/sudoers.d/nopasswd'
    mode: 0440

- name: Copy renew cert script
  copy:
    src: 'root/renew_cert.sh'
    dest: '/root/renew_cert.sh'
    mode: 0755