- hosts: all
  become: true

  tasks:
  # - name: Print all variables
  #   debug:
  #     var: hostvars[inventory_hostname]

  - name: Install packages
    apt:
      update_cache: yes
      state: latest
      pkg:
      - apache2
      - mariadb-server
      - memcached
      - nodejs
      - php-apcu
      - php-bcmath
      - php-bz2
      - php-cli
      - php-curl
      - php-fpm
      - php-gd
      - php-gmp
      - php-imagick
      - php-imap
      - php-intl
      - php-ldap
      - php-mbstring
      - php-memcache
      - php-mysql
      - php-opcache
      - php-readline
      - php-xml
      - php-zip
      - redis-tools

  - name: Copy ssh private host keys
    copy:
      content: "{{ item.content }}"
      dest: "/etc/ssh/{{ item.name}}"
      mode: 0600
    loop:
      - { name: "ssh_host_ecdsa_key", content:  "{{ ssh.ssh_host_ecdsa_key }}" }
      - { name: "ssh_host_ed25519_key", content:  "{{ ssh.ssh_host_ed25519_key }}" }
      - { name: "ssh_host_rsa_key", content:  "{{ ssh.ssh_host_rsa_key }}" }

  - name: Copy ssh public host keys
    copy:
      src: "etc/ssh/{{ item }}"
      dest: "/etc/ssh/{{ item }}"
      mode: 0644
    loop:
      - "ssh_host_ecdsa_key.pub"
      - "ssh_host_ed25519_key.pub"
      - "ssh_host_rsa_key.pub"

  - name: Copy network interfaces file
    copy:
      src: "etc/network/interfaces"
      dest: "/etc/network/interfaces"
      mode: 0644

  - name: Copy network alias-0 file
    copy:
      src: "etc/network/interfaces.d/eno1_alias_0"
      dest: "/etc/network/interfaces.d/eno1_alias_0"
      mode: 0644

  - name: Copy network alias-1 file
    copy:
      src: "etc/network/interfaces.d/eno1_alias_1"
      dest: "/etc/network/interfaces.d/eno1_alias_1"
      mode: 0644

  - name: Enable Apache proxy modules
    command:
      cmd: a2enmod proxy_fcgi setenvif

  - name: Enable PHP
    command:
      cmd: a2enconf php8.2-fpm

  - name: Reload Apache to apply changes
    ansible.builtin.service:
      name: apache2
      state: reloaded
